apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-pv-0
spec:
  storageClassName: cassandra-localpath-0
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /usr/lib/meteo/cassandra_data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-pvc-0
  # namespace: meteo
spec:
  storageClassName: cassandra-localpath-0
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cassandra-localpath-0
provisioner: rancher.io/local-path
allowVolumeExpansion: true

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra-0
  labels:
    app: cassandra
spec:
  serviceName: cassandra
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: cassandra
    spec:
      terminationGracePeriodSeconds: 1800
      nodeSelector:
        kubernetes.io/hostname: explorer-6
      containers:
        - name: cassandra
          image: docker.io/library/cassandra:4.1.10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          resources:
            limits:
              cpu: "500m"
              memory: 1Gi
            requests:
              cpu: "500m"
              memory: 1Gi
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - nodetool drain
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_SEEDS
              value: cassandra-0-0.cassandra.meteo.svc.cluster.local
            - name: CASSANDRA_CLUSTER_NAME
              value: "k8s-cassandra"
            - name: CASSANDRA_DC
              value: "dc1"
            - name: CASSANDRA_RACK
              value: "rack1"
            - name: CASSANDRA_NUM_TOKENS
              value: "256"
            # Тип snitch (следует указать, если используете DC / rack)
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: "GossipingPropertyFileSnitch"
            - name: CASSANDRA_START_RPC
              value: "true"
            - name: CASSANDRA_RPC_ADDRESS
              value: "0.0.0.0"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CASSANDRA_LISTEN_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CASSANDRA_BROADCAST_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CASSANDRA_BROADCAST_RPC_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

          readinessProbe:
            tcpSocket:
              port: 9042
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 10

          livenessProbe:
            tcpSocket:
              port: 9042
            initialDelaySeconds: 180
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 12

          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra  # directory inside pod in the container
              readOnly: false
      volumes:
        - name: cassandra-data # should match name in spec.containers.volumeMounts
          persistentVolumeClaim:
            claimName: cassandra-pvc-0


#  volumeClaimTemplates:
#    - metadata:
#        name: cassandra-data
#      spec:
#        accessModes: ["ReadWriteOnce"]
#        storageClassName: "standard"  # поменяйте на ваш класс хранилища
#        resources:
#          requests:
#            storage: 20Gi
